@url = http://localhost:3000/graphql
### 
POST {{url}} HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL

query($id: ID){
    chat(id: $id){
      id
      text
    }
}

{
  "id": "2"
}
### 
POST {{url}} HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL

{
    chats{
      id
      text
    }
}

